export const STORAGE_KEYS = {
  wifiEnabled: "wifiEnabled",
  isDarkMode: "isDarkMode",
  screenBrightness: "screenBrightness",
  soundState: "soundState",
  sfxMuted: "sfxMuted",
  sfxVolume: "sfxVolume",
  snakeHighScore: "snakeHighScore",
  snakeState: "snakeState",
  desktopState: "desktopState",
  settingsState: "settingsState",
  notesState: "notesState",
  mediaState: "mediaState",
  weatherState: "weatherState",
  wallpaperId: "wallpaperId",
  accentColorId: "accentColorId",
  fontSize: "fontSize",
  highContrast: "highContrast",
} as const;
